language: node_js
node_js: stable
services:
- postgresql
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
deploy:
  provider: heroku
  api_key:
    secure: h2K0TLRiHkJmm7x2fVBZdrKGlUyZ/EItdsISXt+QTOaVIJM4p6HeNfH8gXqMBeXiAjNSTcAe1+9F/1hb2H8JY1YRRWyUw8aKo/61RSTMjmRBgPSdFkpOYgpgpZ33SasrVCqb2dFO98CkSNGQs9yG3ckD65Ni9IbGMDxzD7kvwxq13sarG7FSnshG+zIa1rHedOxv7bIDW8EmFFcX9JHBQXjT9BqAkENGN/GY5yjL7GFiUPNq5vIkDLS/Wl0LHNDWhS1HvABUwPT47jqCRAeThp6VGGL4hVgjS8vM96y3qiVuNtYMF6rQYstjJGPQnyLVtjUWr1nYlLr//Scym3QOcFkC85/LhaTYGu61H7oQndwB4EIZKS2o+Zg/FfwZT3Q1aKhUr2lKdTqxb8Bfhl1CLuD9SHjy/tQX/yCD61RFFYStMyDotBwMrp4xxBHgDrqEGLrJ/p+NHdPhXE9pxHHHB3ombPms5Q5AYtDfPQiGHCx72C9M0HeFzNFphA7NZiPLDY8Gal8/G2VsoS533wndDwj1EuBtJJ3zDV3+oNfXHRrLqmTXS4JfHzUGmee/UF+7Tg58ZkTN5mwrZq8uDVaPNxalfTFXrG2QLyolZ+w1WdvUfXuBPSOz+iXmZeLyDf0IQbW78o6CZNRr/U9D+pUGGm3yuTAS/Q33jt1gB6IpS1M=
  app: teamwork-app-staging
  on:
    repo: chubbystrings/Teamwork_App
install:
- npm install
script:
- npm run test-prod
env:
  global:
    secure: G74dyVXyP3xXMjWD2kWZYGuacewqA7Mc5sZ7ig8L+2MhV0v+GLqeVwy2nw/JirdfJmqCnGypyLbY+USMb89TPp02ghEmSarBeKCF9GtjLasxs8WNu8qmGEbOcaKYGJyUDtPie+1wWB0FoQbSnxFzdC9r7fJwu2maVMdTkiZSXjElt0yybbXU3aqV9MkhisnLpxsc/vK3fE580py4CyHr4wYQhXOPxWq+XiRXDCgucbiLHhqBS2YqHnYyUgXC5B8hP60SSNR9TyjfvoYp/FhcvLrQ4PdcawUtxckBBNF16tQVUY2eARAGz/1KM/DRHE1gMQuby55Qzr38S3A+tNJwvhVn87kba5rg4WIzoyc6kK1iKasoRMPDBicn/Qwk3PpqKyrITrYXPs5sYciB5rh9rNjWiJRZ2YeJI6jlN0aIBOQJSUDG/9lIkjHMWLFqWqXB252egI5aa1J/Aa0sROpXJuNiCqrDtsZh7NpvWpy+E3uW0ZIq6uVFMZpevWm5+cs/p/gO/QZFXeik32HGNO4cd6JT6AHfxsYz7iAhcxBLnzB5EbIexZaCpzfEIiDf1nBDTaMeKZaiUwhxJocwkDxTNHQDbJxZWB65+3fYFii8o+EqWve9DtzhI95GA6308XTMoDDDnAy6LP2r9JnhTn/SLYpc6r41VWUL3kf11dzOZyI=
